#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

function changed {
  	git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
	npm ci
  	echo "📦 package-lock.json changed. Running npm ci to bring your dependencies up to date."
fi